(function exposeForgeMockData(global) {
  'use strict';

  const blockingIssue = {
    id: 'issue-01',
    type: 'issue',
    title: '阻断问题 I-01',
    summary: '开场缺少能持续牵引读者的异常信号，父亲失踪线索出现得太晚。',
    status: 'verified',
    time: '10:18',
    linkedTimelineId: 'turn-03',
  };

  const revisionInstruction = {
    id: 'revision-01',
    type: 'instruction',
    title: '返修指令 R-01',
    summary: '只改写开场六行：前置口哨线索，保留雨夜码头与第一人称视角。',
    status: 'applied',
    time: '10:24',
    linkedTimelineId: 'turn-04',
  };

  const verifiedEvent = {
    id: 'verified-01',
    type: 'verified',
    title: '复核事件 V-01',
    summary: '异常信号已前置，返修未越过冻结范围，阻断问题通过独立复核。',
    status: 'verified',
    time: '10:46',
    linkedTimelineId: 'turn-06',
  };

  const artifactVersions = [
    {
      id: 'version-01',
      type: 'version',
      label: '稿件 v1',
      title: '初稿 v1',
      summary: '完成基础场景与失踪线索铺设，等待审核。',
      status: 'superseded',
      time: '10:08',
      linkedTimelineId: 'turn-02',
      valid: false,
      current: false,
      lines: [
        '雨把码头的灯切成一截一截。',
        '我在凌晨两点收到母亲的语音。',
        '她说，旧仓库里还留着父亲的录音带。',
        '我撑伞走过空无一人的防波堤。',
        '门锁生锈，我花了很久才推开。',
        '录音里，父亲第一次说起那场失踪。',
      ],
    },
    {
      id: 'version-02',
      type: 'version',
      label: '稿件 v2',
      title: '返修稿 v2',
      summary: '前置异常信号并完成定点返修，进入复核。',
      status: 'verified',
      time: '10:39',
      linkedTimelineId: 'turn-05',
      valid: true,
      current: false,
      lines: [
        '雨把码头的灯切成一截一截，像被谁反复剪辑的旧胶片。',
        '凌晨两点，母亲发来一条只有七秒的语音。',
        '“别去旧仓库。”她说。背景里却响起父亲失踪前常吹的口哨。',
        '我把伞留在风里，沿着防波堤一路跑过去。',
        '门锁没有锈——昨晚刚有人换过。',
        '录音机仍在转，父亲的声音从黑暗里叫出了我的小名。',
      ],
    },
    {
      id: 'version-03',
      type: 'version',
      label: '交付稿 v3',
      title: '交付稿 v3',
      summary: '复核后完成标点与节奏微调，当前有效交付版本。',
      status: 'delivered',
      time: '10:58',
      linkedTimelineId: 'turn-07',
      valid: true,
      current: true,
      lines: [
        '雨把码头的灯切成一截一截，像被谁反复剪辑的旧胶片。',
        '凌晨两点，母亲发来一条只有七秒的语音。',
        '“别去旧仓库。”',
        '她的背景里，却响起父亲失踪前常吹的口哨。',
        '我把伞留在风里，沿着防波堤一路跑过去。',
        '门锁没有锈——昨晚刚有人换过。',
        '录音机仍在转。',
        '父亲的声音从黑暗里叫出了我的小名。',
      ],
    },
  ];

  const primaryTask = {
    id: 'task-fog-06',
    displayId: '任务 F-026',
    title: '雾港来信',
    template: '悬疑短篇生产线',
    phase: '系统门禁完成',
    status: 'delivered',
    updatedAt: '今天 10:58',
    createdAt: '今天 09:42',
    progress: 100,
    summary: '一封来自失踪父亲的录音，让主人公在雨夜重返封存多年的旧码头。',
    owner: '内容实验室',
    artifactTitle: '《雾港来信》终稿',
    agents: [
      {
        id: 'agent-01',
        name: '流程总控',
        role: '编排与门禁',
        provider: 'DeepSeek',
        model: 'deepseek-v4-pro',
        modelSource: '场景默认配置',
        color: '#B45642',
        status: 'completed',
      },
      {
        id: 'agent-02',
        name: '正文写作者',
        role: '正文生成与定点返修',
        provider: 'DeepSeek',
        model: 'deepseek-v4-flash',
        modelSource: '角色级覆盖',
        color: '#526A5A',
        status: 'completed',
      },
      {
        id: 'agent-03',
        name: '内容审核员',
        role: '问题识别与复核',
        provider: 'DeepSeek',
        model: 'deepseek-v4-pro',
        modelSource: '场景默认配置',
        color: '#8A6848',
        status: 'completed',
      },
      {
        id: 'agent-04',
        name: '交付核验员',
        role: '版本与门禁核对',
        provider: '本地规则',
        model: 'delivery-gate',
        modelSource: '系统规则引擎',
        color: '#68707C',
        status: 'completed',
      },
    ],
    turns: [
      {
        id: 'turn-01',
        agentId: 'agent-01',
        sequence: '01',
        title: '拆解生产目标',
        summary: '确认悬疑短篇的视角、篇幅与交付门禁，并将正文任务路由给写作者。',
        time: '09:48',
        duration: '18.4s',
        status: 'completed',
        kind: 'brief',
        input: {
          text: '根据“悬疑短篇生产线”模板生产一篇约 8,000 字的第一人称故事。核心素材是一盘来自失踪父亲的录音，故事需要在雨夜旧码头展开，并通过系统交付门禁。',
          attachments: [{ id: 'task-input', label: '原始故事素材', kind: 'input' }],
        },
        reasoningSummary: '先把不可变约束、正文目标和交付条件拆开，再将正文生成任务交给写作者，避免模型在首轮就混入审核结论。',
        toolCalls: [
          {
            id: 'tool-01-a',
            name: '读取模板配置',
            status: 'completed',
            duration: '0.4s',
            arguments: '{ "template": "悬疑短篇生产线", "version": "current" }',
            result: '读取到 4 个执行角色、3 项文本输入约束和 4 项交付检查。',
          },
        ],
        output: {
          text: '生产目标已拆解：第一人称，雨夜旧码头，父亲失踪录音为核心钩子；正文先完成可审核初稿，再根据阻断 Issue 进行定点返修。下一步由正文写作者生成 v1。',
        },
        systemEvents: ['绑定场景模板当前版本', '把正文生成请求路由至正文写作者'],
        graph: {
          inputFrom: 'task-input',
          outputNodeId: 'turn-01-output',
          routedTo: 'turn-02',
        },
      },
      {
        id: 'turn-02',
        agentId: 'agent-02',
        sequence: '02',
        title: '提交初稿 v1',
        summary: '完成雨夜码头场景、人物动机与父亲失踪线索的第一版正文。',
        time: '10:08',
        duration: '2m 46s',
        status: 'completed',
        kind: 'artifact',
        linkedEvolutionId: 'version-01',
        input: {
          text: '执行总控下发的正文任务：严格使用第一人称，围绕雨夜旧码头和失踪父亲录音展开，先生成完整可审核初稿，不提前处理尚未出现的审核意见。',
          attachments: [{ id: 'turn-01-output', label: '生产目标与写作约束', kind: 'message' }],
        },
        reasoningSummary: '以录音作为行动动机，以码头空间逐步释放父亲失踪线索；先保证完整叙事，再交给审核角色判断阅读钩子是否足够前置。',
        toolCalls: [
          {
            id: 'tool-02-a',
            name: '读取故事素材',
            status: 'completed',
            duration: '0.7s',
            arguments: '{ "source": "task-input", "section": "all" }',
            result: '读取人物、地点、录音和旧码头四组素材。',
          },
          {
            id: 'tool-02-b',
            name: '提交产物版本',
            status: 'completed',
            duration: '1.2s',
            arguments: '{ "artifact": "正文", "parent": null, "label": "v1" }',
            result: '正文 v1 已追加保存并进入审核队列。',
          },
        ],
        output: {
          text: '初稿已经完成。故事从主人公收到旧录音开始，随后进入雨夜码头，在防波堤、旧仓库和仍在转动的录音机之间逐步揭开父亲留下的线索。',
        },
        systemEvents: ['追加保存正文 v1', '将 v1 路由给内容审核员'],
        graph: {
          inputFrom: 'turn-01-output',
          outputNodeId: 'version-01',
          routedTo: 'turn-03',
        },
      },
      {
        id: 'turn-03',
        agentId: 'agent-03',
        sequence: '03',
        title: '提出阻断问题',
        summary: '审核认为开场异常信号过晚，无法在首屏形成持续阅读动力。',
        time: '10:18',
        duration: '1m 12s',
        status: 'completed',
        kind: 'review',
        linkedEvolutionId: 'issue-01',
        input: {
          text: '审核正文 v1，重点判断首屏阅读动力、异常信号出现位置、人物行动因果和悬疑信息的持续释放。只有可复现且阻断交付的问题才能创建 Issue。',
          attachments: [{ id: 'version-01', label: '正文 v1', kind: 'artifact' }],
        },
        reasoningSummary: '正文主体因果完整，但真正异常的“父亲口哨”出现过晚；读者需要在开场就获得一个无法用普通来信解释的信号。',
        toolCalls: [
          {
            id: 'tool-03-a',
            name: '定位正文证据',
            status: 'completed',
            duration: '0.6s',
            arguments: '{ "version": "v1", "query": "父亲口哨" }',
            result: '异常线索首次出现于正文第 17 段。',
          },
          {
            id: 'tool-03-b',
            name: '创建阻断 Issue',
            status: 'completed',
            duration: '0.8s',
            arguments: '{ "version": "v1", "severity": "blocking", "scope": "开场六行" }',
            result: 'Issue I-01 已追加记录，等待总控生成返修指令。',
          },
        ],
        output: {
          text: '提出阻断 Issue I-01：开场异常信号过晚。建议只修改开场六行，把父亲口哨前置，其余段落保持不变，避免返修扩大范围。',
        },
        systemEvents: ['追加 Issue I-01', '把阻断 Issue 路由至流程总控'],
        graph: {
          inputFrom: 'version-01',
          outputNodeId: 'issue-01',
          routedTo: 'turn-04',
        },
      },
      {
        id: 'turn-04',
        agentId: 'agent-01',
        sequence: '04',
        title: '下发定点返修',
        summary: '冻结其余段落，只允许调整开场六行并前置父亲口哨这一异常线索。',
        time: '10:24',
        duration: '22.1s',
        status: 'completed',
        kind: 'instruction',
        linkedEvolutionId: 'revision-01',
        input: {
          text: '根据 Issue I-01 生成可机械校验的返修范围。不得把审核意见直接视为已修复，也不得允许写作者改动 Issue 之外的正文。',
          attachments: [
            { id: 'version-01', label: '正文 v1', kind: 'artifact' },
            { id: 'issue-01', label: 'Issue I-01', kind: 'issue' },
          ],
        },
        reasoningSummary: 'Issue 已明确证据和目标，因此将开场六行设为 editable，其余正文设为 frozen，并要求新版本继续以 v1 为父版本。',
        toolCalls: [
          {
            id: 'tool-04-a',
            name: '创建返修指令',
            status: 'completed',
            duration: '0.9s',
            arguments: '{ "issue": "I-01", "editable": "开场六行", "frozen": "其余正文" }',
            result: '返修指令 R-01 已追加保存并绑定正文写作者。',
          },
        ],
        output: {
          text: '返修指令 R-01：只重写开场六行，将父亲口哨前置为第一处异常信号；其余段落冻结，不得修改。返修稿必须以正文 v1 为父版本。',
        },
        systemEvents: ['追加返修指令 R-01', '把返修任务路由至正文写作者'],
        graph: {
          inputFrom: 'issue-01',
          outputNodeId: 'revision-01',
          routedTo: 'turn-05',
        },
      },
      {
        id: 'turn-05',
        agentId: 'agent-02',
        sequence: '05',
        title: '提交返修稿 v2',
        summary: '按限定范围重写开场，没有改动冻结内容，等待独立复核。',
        time: '10:39',
        duration: '1m 34s',
        status: 'completed',
        kind: 'artifact',
        linkedEvolutionId: 'version-02',
        input: {
          text: '执行返修指令 R-01：只修改开场六行，前置父亲口哨，其余正文必须与 v1 保持一致。提交新版本时声明父版本和修改范围。',
          attachments: [
            { id: 'version-01', label: '正文 v1', kind: 'artifact' },
            { id: 'revision-01', label: '返修指令 R-01', kind: 'revision' },
          ],
        },
        reasoningSummary: '保留原开场天气与地点，只把录音中的父亲口哨提到第一屏；通过最小改动让异常信号提前，同时避免破坏后文线索节奏。',
        toolCalls: [
          {
            id: 'tool-05-a',
            name: '读取返修范围',
            status: 'completed',
            duration: '0.5s',
            arguments: '{ "revision": "R-01" }',
            result: 'editable：开场六行；frozen：其余正文。',
          },
          {
            id: 'tool-05-b',
            name: '提交返修版本',
            status: 'completed',
            duration: '1.1s',
            arguments: '{ "artifact": "正文", "parent": "v1", "label": "v2" }',
            result: '正文 v2 已追加保存，范围校验等待审核角色复核。',
          },
        ],
        output: {
          text: '返修稿 v2 已提交。父亲口哨已前置到开场录音，除开场六行外没有修改其他正文。',
        },
        systemEvents: ['追加保存正文 v2', '记录父版本 v1', '将 v2 路由给内容审核员复核'],
        graph: {
          inputFrom: 'revision-01',
          outputNodeId: 'version-02',
          routedTo: 'turn-06',
        },
      },
      {
        id: 'turn-06',
        agentId: 'agent-03',
        sequence: '06',
        title: '复核返修结果',
        summary: '阻断问题已修复，范围校验通过，审核事件标记为 verified。',
        time: '10:46',
        duration: '48.7s',
        status: 'completed',
        kind: 'review',
        linkedEvolutionId: 'verified-01',
        input: {
          text: '独立复核正文 v2：验证 Issue I-01 的问题是否真正修复，并确认修改没有越过 R-01 的 editable 范围。不得把写作者的 claimed_fixed 当作 verified。',
          attachments: [
            { id: 'version-01', label: '正文 v1', kind: 'artifact' },
            { id: 'version-02', label: '正文 v2', kind: 'artifact' },
            { id: 'issue-01', label: 'Issue I-01', kind: 'issue' },
          ],
        },
        reasoningSummary: 'v2 已在首屏提供父亲口哨这一异常信号；Diff 仅覆盖开场六行，因此内容问题和返修范围可以分别验证通过。',
        toolCalls: [
          {
            id: 'tool-06-a',
            name: '比较版本范围',
            status: 'completed',
            duration: '0.9s',
            arguments: '{ "before": "v1", "after": "v2", "scope": "R-01" }',
            result: '所有 changed 行均位于 editable 范围，scope violation 为 0。',
          },
          {
            id: 'tool-06-b',
            name: '验证 Issue',
            status: 'completed',
            duration: '0.6s',
            arguments: '{ "issue": "I-01", "version": "v2" }',
            result: 'Issue I-01 已由审核角色独立标记为 verified。',
          },
        ],
        output: {
          text: '复核通过：父亲口哨已经前置，首屏阅读动力成立；返修没有修改冻结内容。Issue I-01 状态更新为 verified。',
        },
        systemEvents: ['追加 verified 审核事件', '将有效候选版本路由至交付核验员'],
        graph: {
          inputFrom: 'version-02',
          outputNodeId: 'verified-01',
          routedTo: 'turn-07',
        },
      },
      {
        id: 'turn-07',
        agentId: 'agent-04',
        sequence: '07',
        title: '通过系统交付门禁',
        summary: '四项交付检查全部通过，系统确认 v3 为当前有效交付版本。',
        time: '10:58',
        duration: '6.3s',
        status: 'completed',
        kind: 'delivery',
        linkedEvolutionId: 'version-03',
        input: {
          text: '对当前候选版本执行系统交付门禁：版本必须有效、阻断 Issue 必须 verified、不得存在未完成返修、所有 Turn 必须持久化完成。',
          attachments: [
            { id: 'version-02', label: '正文 v2', kind: 'artifact' },
            { id: 'verified-01', label: 'I-01 验证事件', kind: 'verification' },
          ],
        },
        reasoningSummary: '该角色是本地规则核验，不产生模型隐藏推理；界面展示的是每项机械门禁的输入证据和判定结果。',
        toolCalls: [
          {
            id: 'tool-07-a',
            name: '执行交付门禁',
            status: 'completed',
            duration: '1.4s',
            arguments: '{ "candidate": "v2", "checks": "all" }',
            result: '版本、Issue、返修和 Turn 四项检查全部通过。',
          },
          {
            id: 'tool-07-b',
            name: '确认交付版本',
            status: 'completed',
            duration: '0.7s',
            arguments: '{ "candidate": "v2", "deliveryLabel": "v3" }',
            result: '系统追加交付版本 v3，并将 Case 标记为 delivered。',
          },
        ],
        output: {
          text: '交付门禁通过。正文 v3 已成为当前有效交付版本，任务进入已交付终态。',
        },
        systemEvents: ['追加交付版本 v3', 'Case 状态变更为 delivered', '冻结运行控制'],
        graph: {
          inputFrom: 'verified-01',
          outputNodeId: 'version-03',
          routedTo: null,
        },
      },
    ],
    artifactVersions,
    blockingIssue,
    revisionInstruction,
    verifiedEvent,
    evolution: [
      {
        id: artifactVersions[0].id,
        type: artifactVersions[0].type,
        title: artifactVersions[0].title,
        summary: artifactVersions[0].summary,
        status: artifactVersions[0].status,
        time: artifactVersions[0].time,
        linkedTimelineId: artifactVersions[0].linkedTimelineId,
      },
      blockingIssue,
      revisionInstruction,
      {
        id: artifactVersions[1].id,
        type: artifactVersions[1].type,
        title: artifactVersions[1].title,
        summary: artifactVersions[1].summary,
        status: artifactVersions[1].status,
        time: artifactVersions[1].time,
        linkedTimelineId: artifactVersions[1].linkedTimelineId,
      },
      verifiedEvent,
      {
        id: artifactVersions[2].id,
        type: artifactVersions[2].type,
        title: artifactVersions[2].title,
        summary: artifactVersions[2].summary,
        status: artifactVersions[2].status,
        time: artifactVersions[2].time,
        linkedTimelineId: artifactVersions[2].linkedTimelineId,
      },
    ],
    deliveryChecks: [
      {
        id: 'check-version',
        label: '当前版本有效',
        detail: 'v3 有效且未被后续版本替代',
        status: 'passed',
      },
      {
        id: 'check-review',
        label: '审核已通过',
        detail: '关联复核事件为 verified',
        status: 'passed',
      },
      {
        id: 'check-issues',
        label: '阻断问题已验证',
        detail: 'I-01 已由审核角色独立复核',
        status: 'passed',
      },
      {
        id: 'check-turns',
        label: '没有未完成轮次',
        detail: '全部 7 个 Turn 均已持久化完成',
        status: 'passed',
      },
    ],
  };

  global.FORGE_MOCK_DATA = {
    tasks: [
      primaryTask,
      {
        id: 'task-rain-01',
        displayId: '任务 R-104',
        title: '雨夜故事',
        template: '现实情感短篇',
        phase: '正文写作',
        status: 'running',
        updatedAt: '3 分钟前',
        progress: 68,
        summary: '正在生成第二章节，当前轮次由正文写作者执行。',
      },
      {
        id: 'task-oldcity-02',
        displayId: '任务 C-018',
        title: '旧城来信',
        template: '年代长篇模板',
        phase: '等待审核',
        status: 'waiting',
        updatedAt: '12 分钟前',
        progress: 54,
        summary: '初稿已提交，等待审核角色领取下一轮。',
      },
      {
        id: 'task-tide-03',
        displayId: '任务 T-071',
        title: '潮汐以北',
        template: '都市悬疑短篇',
        phase: '定点返修',
        status: 'repairing',
        updatedAt: '26 分钟前',
        progress: 76,
        summary: '一项阻断问题正在按行级范围返修。',
      },
      {
        id: 'task-window-04',
        displayId: '任务 W-033',
        title: '窗后的春天',
        template: '家庭情感故事',
        phase: '准备输入',
        status: 'draft',
        updatedAt: '昨天 18:20',
        progress: 8,
        summary: '草稿已保存，尚未进入生产运行。',
      },
      {
        id: 'task-summer-05',
        displayId: '任务 S-012',
        title: '夏末航线',
        template: '成长公路短篇',
        phase: '运行中断',
        status: 'failed',
        updatedAt: '昨天 14:06',
        progress: 41,
        summary: '模拟的模型响应超时，等待人工查看后重试。',
      },
    ],
    templates: [
      {
        id: 'template-short',
        name: '知乎盐选短篇',
        category: '故事生产',
        description: '从故事方向、大纲、章节到终稿的受控多 Agent 流程。',
        stages: 6,
        updatedAt: '本周更新',
      },
      {
        id: 'template-review',
        name: '定点返修工作流',
        category: '审核与返修',
        description: '将审核问题转成 editable / frozen 范围明确的返修任务。',
        stages: 4,
        updatedAt: '稳定版本',
      },
      {
        id: 'template-copy',
        name: '通用文案质检',
        category: '内容工具',
        description: '面向通用文案的生成、质检、复核与交付门禁模板。',
        stages: 3,
        updatedAt: '示例模板',
      },
    ],
    primaryTask,
  };
})(window);
