(function exposeForgeMockData(global) {
  'use strict';

  const blockingIssue = {
    id: 'issue-01',
    type: 'issue',
    title: '阻断问题 I-01',
    summary: '开场缺少能持续牵引读者的异常信号，父亲失踪线索出现得太晚。',
    status: 'verified',
    time: '10:18',
    linkedTimelineId: 'turn-03',
  };

  const revisionInstruction = {
    id: 'revision-01',
    type: 'instruction',
    title: '返修指令 R-01',
    summary: '只改写开场六行：前置口哨线索，保留雨夜码头与第一人称视角。',
    status: 'applied',
    time: '10:24',
    linkedTimelineId: 'turn-04',
  };

  const verifiedEvent = {
    id: 'verified-01',
    type: 'verified',
    title: '复核事件 V-01',
    summary: '异常信号已前置，返修未越过冻结范围，阻断问题通过独立复核。',
    status: 'verified',
    time: '10:46',
    linkedTimelineId: 'turn-06',
  };

  const artifactVersions = [
    {
      id: 'version-01',
      type: 'version',
      label: '稿件 v1',
      title: '初稿 v1',
      summary: '完成基础场景与失踪线索铺设，等待审核。',
      status: 'superseded',
      time: '10:08',
      linkedTimelineId: 'turn-02',
      valid: false,
      current: false,
      lines: [
        '雨把码头的灯切成一截一截。',
        '我在凌晨两点收到母亲的语音。',
        '她说，旧仓库里还留着父亲的录音带。',
        '我撑伞走过空无一人的防波堤。',
        '门锁生锈，我花了很久才推开。',
        '录音里，父亲第一次说起那场失踪。',
      ],
    },
    {
      id: 'version-02',
      type: 'version',
      label: '稿件 v2',
      title: '返修稿 v2',
      summary: '前置异常信号并完成定点返修，进入复核。',
      status: 'verified',
      time: '10:39',
      linkedTimelineId: 'turn-05',
      valid: true,
      current: false,
      lines: [
        '雨把码头的灯切成一截一截，像被谁反复剪辑的旧胶片。',
        '凌晨两点，母亲发来一条只有七秒的语音。',
        '“别去旧仓库。”她说。背景里却响起父亲失踪前常吹的口哨。',
        '我把伞留在风里，沿着防波堤一路跑过去。',
        '门锁没有锈——昨晚刚有人换过。',
        '录音机仍在转，父亲的声音从黑暗里叫出了我的小名。',
      ],
    },
    {
      id: 'version-03',
      type: 'version',
      label: '交付稿 v3',
      title: '交付稿 v3',
      summary: '复核后完成标点与节奏微调，当前有效交付版本。',
      status: 'delivered',
      time: '10:58',
      linkedTimelineId: 'turn-07',
      valid: true,
      current: true,
      lines: [
        '雨把码头的灯切成一截一截，像被谁反复剪辑的旧胶片。',
        '凌晨两点，母亲发来一条只有七秒的语音。',
        '“别去旧仓库。”',
        '她的背景里，却响起父亲失踪前常吹的口哨。',
        '我把伞留在风里，沿着防波堤一路跑过去。',
        '门锁没有锈——昨晚刚有人换过。',
        '录音机仍在转。',
        '父亲的声音从黑暗里叫出了我的小名。',
      ],
    },
  ];

  const primaryTask = {
    id: 'task-fog-06',
    displayId: '任务 F-026',
    title: '雾港来信',
    template: '悬疑短篇生产线',
    phase: '系统门禁完成',
    status: 'delivered',
    updatedAt: '今天 10:58',
    createdAt: '今天 09:42',
    progress: 100,
    summary: '一封来自失踪父亲的录音，让主人公在雨夜重返封存多年的旧码头。',
    owner: '内容实验室',
    artifactTitle: '《雾港来信》终稿',
    agents: [
      {
        id: 'agent-01',
        name: '流程总控',
        role: '编排与门禁',
        provider: 'DeepSeek',
        model: 'deepseek-v4-pro',
        modelSource: '场景默认配置',
        color: '#B45642',
        status: 'completed',
      },
      {
        id: 'agent-02',
        name: '正文写作者',
        role: '正文生成与定点返修',
        provider: 'DeepSeek',
        model: 'deepseek-v4-flash',
        modelSource: '角色级覆盖',
        color: '#526A5A',
        status: 'completed',
      },
      {
        id: 'agent-03',
        name: '内容审核员',
        role: '问题识别与复核',
        provider: 'DeepSeek',
        model: 'deepseek-v4-pro',
        modelSource: '场景默认配置',
        color: '#8A6848',
        status: 'completed',
      },
      {
        id: 'agent-04',
        name: '交付核验员',
        role: '版本与门禁核对',
        provider: '本地规则',
        model: 'delivery-gate',
        modelSource: '系统规则引擎',
        color: '#68707C',
        status: 'completed',
      },
    ],
    turns: [
      {
        id: 'turn-01',
        agentId: 'agent-01',
        sequence: '01',
        title: '拆解生产目标',
        summary: '确认悬疑短篇的视角、篇幅与交付门禁，并将正文任务路由给写作者。',
        time: '09:48',
        status: 'completed',
        kind: 'brief',
      },
      {
        id: 'turn-02',
        agentId: 'agent-02',
        sequence: '02',
        title: '提交初稿 v1',
        summary: '完成雨夜码头场景、人物动机与父亲失踪线索的第一版正文。',
        time: '10:08',
        status: 'completed',
        kind: 'artifact',
        linkedEvolutionId: 'version-01',
      },
      {
        id: 'turn-03',
        agentId: 'agent-03',
        sequence: '03',
        title: '提出阻断问题',
        summary: '审核认为开场异常信号过晚，无法在首屏形成持续阅读动力。',
        time: '10:18',
        status: 'completed',
        kind: 'review',
        linkedEvolutionId: 'issue-01',
      },
      {
        id: 'turn-04',
        agentId: 'agent-01',
        sequence: '04',
        title: '下发定点返修',
        summary: '冻结其余段落，只允许调整开场六行并前置父亲口哨这一异常线索。',
        time: '10:24',
        status: 'completed',
        kind: 'instruction',
        linkedEvolutionId: 'revision-01',
      },
      {
        id: 'turn-05',
        agentId: 'agent-02',
        sequence: '05',
        title: '提交返修稿 v2',
        summary: '按限定范围重写开场，没有改动冻结内容，等待独立复核。',
        time: '10:39',
        status: 'completed',
        kind: 'artifact',
        linkedEvolutionId: 'version-02',
      },
      {
        id: 'turn-06',
        agentId: 'agent-03',
        sequence: '06',
        title: '复核返修结果',
        summary: '阻断问题已修复，范围校验通过，审核事件标记为 verified。',
        time: '10:46',
        status: 'completed',
        kind: 'review',
        linkedEvolutionId: 'verified-01',
      },
      {
        id: 'turn-07',
        agentId: 'agent-04',
        sequence: '07',
        title: '通过系统交付门禁',
        summary: '四项交付检查全部通过，系统确认 v3 为当前有效交付版本。',
        time: '10:58',
        status: 'completed',
        kind: 'delivery',
        linkedEvolutionId: 'version-03',
      },
    ],
    artifactVersions,
    blockingIssue,
    revisionInstruction,
    verifiedEvent,
    evolution: [
      {
        id: artifactVersions[0].id,
        type: artifactVersions[0].type,
        title: artifactVersions[0].title,
        summary: artifactVersions[0].summary,
        status: artifactVersions[0].status,
        time: artifactVersions[0].time,
        linkedTimelineId: artifactVersions[0].linkedTimelineId,
      },
      blockingIssue,
      revisionInstruction,
      {
        id: artifactVersions[1].id,
        type: artifactVersions[1].type,
        title: artifactVersions[1].title,
        summary: artifactVersions[1].summary,
        status: artifactVersions[1].status,
        time: artifactVersions[1].time,
        linkedTimelineId: artifactVersions[1].linkedTimelineId,
      },
      verifiedEvent,
      {
        id: artifactVersions[2].id,
        type: artifactVersions[2].type,
        title: artifactVersions[2].title,
        summary: artifactVersions[2].summary,
        status: artifactVersions[2].status,
        time: artifactVersions[2].time,
        linkedTimelineId: artifactVersions[2].linkedTimelineId,
      },
    ],
    deliveryChecks: [
      {
        id: 'check-version',
        label: '当前版本有效',
        detail: 'v3 有效且未被后续版本替代',
        status: 'passed',
      },
      {
        id: 'check-review',
        label: '审核已通过',
        detail: '关联复核事件为 verified',
        status: 'passed',
      },
      {
        id: 'check-issues',
        label: '阻断问题已验证',
        detail: 'I-01 已由审核角色独立复核',
        status: 'passed',
      },
      {
        id: 'check-turns',
        label: '没有未完成轮次',
        detail: '全部 7 个 Turn 均已持久化完成',
        status: 'passed',
      },
    ],
  };

  global.FORGE_MOCK_DATA = {
    tasks: [
      primaryTask,
      {
        id: 'task-rain-01',
        displayId: '任务 R-104',
        title: '雨夜故事',
        template: '现实情感短篇',
        phase: '正文写作',
        status: 'running',
        updatedAt: '3 分钟前',
        progress: 68,
        summary: '正在生成第二章节，当前轮次由正文写作者执行。',
      },
      {
        id: 'task-oldcity-02',
        displayId: '任务 C-018',
        title: '旧城来信',
        template: '年代长篇模板',
        phase: '等待审核',
        status: 'waiting',
        updatedAt: '12 分钟前',
        progress: 54,
        summary: '初稿已提交，等待审核角色领取下一轮。',
      },
      {
        id: 'task-tide-03',
        displayId: '任务 T-071',
        title: '潮汐以北',
        template: '都市悬疑短篇',
        phase: '定点返修',
        status: 'repairing',
        updatedAt: '26 分钟前',
        progress: 76,
        summary: '一项阻断问题正在按行级范围返修。',
      },
      {
        id: 'task-window-04',
        displayId: '任务 W-033',
        title: '窗后的春天',
        template: '家庭情感故事',
        phase: '准备输入',
        status: 'draft',
        updatedAt: '昨天 18:20',
        progress: 8,
        summary: '草稿已保存，尚未进入生产运行。',
      },
      {
        id: 'task-summer-05',
        displayId: '任务 S-012',
        title: '夏末航线',
        template: '成长公路短篇',
        phase: '运行中断',
        status: 'failed',
        updatedAt: '昨天 14:06',
        progress: 41,
        summary: '模拟的模型响应超时，等待人工查看后重试。',
      },
    ],
    templates: [
      {
        id: 'template-short',
        name: '知乎盐选短篇',
        category: '故事生产',
        description: '从故事方向、大纲、章节到终稿的受控多 Agent 流程。',
        stages: 6,
        updatedAt: '本周更新',
      },
      {
        id: 'template-review',
        name: '定点返修工作流',
        category: '审核与返修',
        description: '将审核问题转成 editable / frozen 范围明确的返修任务。',
        stages: 4,
        updatedAt: '稳定版本',
      },
      {
        id: 'template-copy',
        name: '通用文案质检',
        category: '内容工具',
        description: '面向通用文案的生成、质检、复核与交付门禁模板。',
        stages: 3,
        updatedAt: '示例模板',
      },
    ],
    primaryTask,
  };
})(window);
